name: Collect HTV coins

on:
  workflow_dispatch:  # Permite ejecución manual inmediata

env:
  HTV_EMAIL: "${{ secrets.HTV_EMAIL }}"
  HTV_PASSWORD: "${{ secrets.HTV_PASSWORD }}"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: styfle/cancel-workflow-action@0.9.0
        name: "Cancelling duplicate workflow runs"
        with:
          all_but_latest: true
          access_token: ${{ github.token }}
      - name: Install Dependencies
        run: |
          sudo apt update && sudo apt install -y curl openssl jq
      - name: Collect Coins
        run: |
          chmod +x coins.sh
          ./coins.sh
      - name: Commit session file
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add .
          git commit -m "auto: update session" -a || true
      - name: push session
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ github.token }}
          branch: ${{ github.ref }}
      # Paso adicional para esperar 3 horas y reiniciar el flujo
      - name: Wait and rerun
        run: |
          echo "Esperando 3 horas antes de reiniciar..."
          sleep $((3 * 60 * 60))  # Espera 3 horas (3*60*60 segundos)
          echo "Reiniciando el workflow..."
          gh workflow run "<nombre-del-workflow>.yml"
